name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create google-services.json from secret
      run: |
          mkdir -p firebase-ai/app/src/release
          echo "${{ secrets.FIREBASE_SERVICES_JSON }}" | base64 --decode > firebase-ai/app/src/release/google-services.json
          echo "${{ secrets.FIREBASE_SERVICES_JSON }}" | base64 --decode > firebase-ai/app/google-services.json
  
          if [ -f firebase-ai/app/src/release/google-services.json ]; then
            echo "google-services.json file created successfully."
          else
            echo "Error: google-services.json file was not created."
          fi
          
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x firebase-ai/gradlew

    
    # Build with Gradle
    - name: Build with Gradle
      run: ./firebase-ai/gradlew assembleRelease

    # Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app.apk
        path: firebase-ai/app/build/outputs/apk/release/app-release.apk
        retention-days: 1

    - name: List Files
      run: |
          cd firebase-ai
          ls -R
