name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Build with Gradle
    - name: Build with Gradle
      run: ./firebase-ai/gradlew build

    # Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 1
